"""user

Revision ID: 287246e5974d
Revises: 
Create Date: 2023-05-22 12:21:37.785399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287246e5974d'
down_revision = None  # type: ignore
branch_labels = None  # type: ignore
depends_on = None  # type: ignore



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
